// 流水线看板演示数据
export const pipelines = [
  {
    id: 1,
    name: 'payment-svc-ci',
    repo: 'git@nexus:pay/payment-svc.git',
    branch: 'main',
    commit: 'a3f9c21',
    actor: 'zhang.san',
    status: 'running',
    duration: '2m 05s',
    stage: '构建镜像',
    progress: 62,
    env: 'prod',
    startedAt: '2026-09-10 10:18:22',
  },
  {
    id: 2,
    name: 'gateway-release',
    repo: 'git@nexus:infra/gateway.git',
    branch: 'release/2.4',
    commit: '77bd10e',
    actor: 'ci-bot',
    status: 'success',
    duration: '3m 12s',
    stage: '已完成',
    progress: 100,
    env: 'prod',
    startedAt: '2026-09-10 10:21:04',
  },
  {
    id: 3,
    name: 'user-center-ci',
    repo: 'git@nexus:uc/user-center.git',
    branch: 'feature/login-refactor',
    commit: 'e8a1145',
    actor: 'li.si',
    status: 'failed',
    duration: '1m 47s',
    stage: '单元测试',
    progress: 35,
    env: 'dev',
    startedAt: '2026-09-10 10:05:51',
  },
  {
    id: 4,
    name: 'data-pipeline-nightly',
    repo: 'git@nexus:data/etl.git',
    branch: 'hotfix/etl-timezone',
    commit: '02cf77a',
    actor: 'wang.wu',
    status: 'running',
    duration: '5m 51s',
    stage: '数据校验',
    progress: 78,
    env: 'staging',
    startedAt: '2026-09-10 09:40:12',
  },
  {
    id: 5,
    name: 'notify-worker-ci',
    repo: 'git@nexus:msg/notify-worker.git',
    branch: 'main',
    commit: '9d0e3b8',
    actor: 'ci-bot',
    status: 'success',
    duration: '2m 02s',
    stage: '已完成',
    progress: 100,
    env: 'staging',
    startedAt: '2026-09-10 09:31:37',
  },
  {
    id: 6,
    name: 'order-svc-canary',
    repo: 'git@nexus:trade/order-svc.git',
    branch: 'main',
    commit: '5b2f880',
    actor: 'zhao.liu',
    status: 'failed',
    duration: '4m 10s',
    stage: '灰度发布',
    progress: 80,
    env: 'prod',
    startedAt: '2026-09-10 08:58:03',
  },
]

export const statusSummary = [
  { key: 'success', label: 'Success', value: 24, icon: 'CircleCheckFilled' },
  { key: 'running', label: 'Running', value: 2, icon: 'Loading' },
  { key: 'failed', label: 'Failed', value: 2, icon: 'CircleCloseFilled' },
]
